In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv('salaries_by_college_major(2008).csv')

df.head(50)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [4]:
cm =pd.read_csv('college_majors_and_graduates/recent-grads.csv')

cm.head(150)

,index,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,0,1,2419,PETROLEUM ENGINEERING,Engineering,2339,36,2057,282,0.120564,...,270,1207,37,0.018381,110000,95000,125000,1534,364,193
1,1,2,2416,MINING AND MINERAL ENGINEERING,Engineering,756,7,679,77,0.101852,...,170,388,85,0.117241,75000,55000,90000,350,257,50
2,2,3,2415,METALLURGICAL ENGINEERING,Engineering,856,3,725,131,0.153037,...,133,340,16,0.024096,73000,50000,105000,456,176,0
3,3,4,2417,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258,16,1123,135,0.107313,...,150,692,40,0.050125,70000,43000,80000,529,102,0
4,4,5,2405,CHEMICAL ENGINEERING,Engineering,32260,289,21239,11021,0.341631,...,5180,16697,1672,0.061098,65000,50000,75000,18314,4440,972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,145,146,5200,PSYCHOLOGY,Psychology & Social Work,393735,2584,86648,307087,0.779933,...,115172,174438,28169,0.083811,31500,24000,41000,125148,141860,48207
146,146,147,6002,MUSIC,Arts,60633,419,15670,12543,0.444582,...,24943,21425,3918,0.075960,31000,22300,42000,13752,28786,9286
147,147,148,2306,PHYSICAL AND HEALTH EDUCATION TEACHING,Education,28213,259,29909,30724,0.506721,...,7230,13651,1920,0.074667,31000,24000,40000,12777,9328,2042
148,148,149,6006,ART HISTORY AND CRITICISM,Humanities & Liberal Arts,21030,204,3240,17790,0.845934,...,6140,9965,1128,0.060298,31000,23000,40000,5139,9738,3426
149,149,150,6000,FINE ARTS,Arts,74440,623,24786,49654,0.667034,...,23656,31877,5486,0.084186,30500,21000,41000,20792,32725,11880

In [6]:
er =pd.read_csv('college_majors_and_graduates/women-stem.csv')

er.head(30)

,index,Rank,Major_code,Major,Major_category,Total,Men,Women,ShareWomen,Median
0,0,1,2419,PETROLEUM ENGINEERING,Engineering,2339,2057,282,0.120564,110000
1,1,2,2416,MINING AND MINERAL ENGINEERING,Engineering,756,679,77,0.101852,75000
2,2,3,2415,METALLURGICAL ENGINEERING,Engineering,856,725,131,0.153037,73000
3,3,4,2417,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258,1123,135,0.107313,70000
4,4,5,2418,NUCLEAR ENGINEERING,Engineering,2573,2200,373,0.144967,65000
5,5,6,2405,CHEMICAL ENGINEERING,Engineering,32260,21239,11021,0.341631,65000
6,6,7,5001,ASTRONOMY AND ASTROPHYSICS,Physical Sciences,1792,832,960,0.535714,62000
7,7,8,2414,MECHANICAL ENGINEERING,Engineering,91227,80320,10907,0.119559,60000
8,8,9,2401,AEROSPACE ENGINEERING,Engineering,15058,12953,2105,0.139793,60000
9,9,10,2408,ELECTRICAL ENGINEERING,Engineering,81527,65511,16016,0.196450,60000
10,10,11,2407,COMPUTER ENGINEERING,Engineering,41542,33258,8284,0.199413,60000
11,11,12,5008,MATERIALS SCIENCE,Engineering,4279,2949,1330,0.310820,60000
12,12,13,2404,BIOMEDICAL ENGINEERING,Engineering,14955,8407,6548,0.437847,60000
13,13,14,2409,ENGINEERING MECHANICS PHYSICS AND SCIENCE,Engineering,4321,3526,795,0.183985,58000
14,14,15,2402,BIOLOGICAL ENGINEERING,Engineering,8925,6062,2863,0.320784,57100
15,15,16,2412,INDUSTRIAL AND MANUFACTURING ENGINEERING,Engineering,18968,12453,6515,0.343473,57000
16,16,17,2400,GENERAL ENGINEERING,Engineering,61152,45683,15469,0.252960,56000
17,17,18,2403,ARCHITECTURAL ENGINEERING,Engineering,2825,1835,990,0.350442,54000
18,18,19,2102,COMPUTER SCIENCE,Computers & Mathematics,128319,99743,28576,0.222695,53000
19,19,20,2502,ELECTRICAL ENGINEERING TECHNOLOGY,Engineering,11565,8181,3384,0.292607,52000
20,20,21,2413,MATERIALS ENGINEERING AND MATERIALS SCIENCE,Engineering,2993,2020,973,0.325092,52000
21,21,22,2499,MISCELLANEOUS ENGINEERING,Engineering,9133,7398,1735,0.189970,50000
22,22,23,2406,CIVIL ENGINEERING,Engineering,53153,41081,12072,0.227118,50000
23,23,24,2500,ENGINEERING TECHNOLOGIES,Engineering,3600,2695,905,0.251389,50000
24,24,25,2411,GEOLOGICAL AND GEOPHYSICAL ENGINEERING,Engineering,720,488,232,0.322222,50000
25,25,26,2410,ENVIRONMENTAL ENGINEERING,Engineering,4047,2662,1385,0.342229,50000
26,26,27,6107,NURSING,Health,209394,21773,187621,0.896019,48000
27,27,28,2503,INDUSTRIAL PRODUCTION TECHNOLOGIES,Engineering,4631,3477,1154,0.249190,46000
28,28,29,5102,"NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL ...",Physical Sciences,2116,528,1588,0.750473,46000
29,29,30,2105,INFORMATION SCIENCES,Computers & Mathematics,11913,9005,2908,0.244103,45000